import { DEFAULT_THEME_TOKENS, type ThemeTokens } from './api'

/**
 * Ready-made theme presets for the Admin > Theme & Colours editor.
 *
 * Each preset is a full, coherent palette — not just a background/text pair.
 * Applying one fills the whole draft (both modes at once) so nothing is left
 * half-matched: buttons, links and icons all follow the same accent, ghost
 * borders and disabled states follow the same neutral family, and swapping
 * presets never mixes one theme's warm neutrals with another's accent.
 *
 * State colours (success/warning/danger/info) are deliberately identical
 * across every preset — they're semantic, not brand, and a red error should
 * still read as "red" regardless of which palette is active.
 *
 * Applying a preset only fills the editor's draft; it still has to be saved
 * like any manual edit, and "Reset to defaults" continues to mean the first
 * entry here (Gold Classic), which is a straight alias of DEFAULT_THEME_TOKENS.
 */

export type ThemePreset = {
  key: string
  labelKey: string
  light: ThemeTokens
  dark: ThemeTokens
}

const STATE_LIGHT = {
  state_success: '#15803D',
  state_warning: '#B45309',
  state_danger: '#DC2626',
  state_info: '#0B4363',
}

const STATE_DARK = {
  state_success: '#22C55E',
  state_warning: '#F59E0B',
  state_danger: '#F87171',
  state_info: '#38BDF8',
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    key: 'gold_classic',
    labelKey: 'theme.preset.goldClassic',
    light: DEFAULT_THEME_TOKENS.light,
    dark: DEFAULT_THEME_TOKENS.dark,
  },
  {
    key: 'midnight_blue',
    labelKey: 'theme.preset.midnightBlue',
    light: {
      bg: '#F5F8FA',
      bg_2: '#EAF1F5',
      surface: '#FFFFFF',
      header_bg: '#F5F8FA',
      footer_bg: '#F5F8FA',
      heading_color: '#0B2733',
      body_text_color: '#0B2733',
      secondary_text_color: '#3A5A66',
      muted_text_color: '#6B8A94',
      link_color: '#0B4363',
      icon_color: '#0B4363',
      btn_fill_bg: '#0B4363',
      btn_fill_bg_hover: '#0A3A57',
      btn_fill_bg_active: '#082E45',
      btn_fill_text: '#FFFFFF',
      btn_fill_border: '#0B4363',
      btn_ghost_text: '#0B2733',
      btn_ghost_border: '#C7D9E0',
      btn_ghost_border_hover: '#6B8A94',
      btn_disabled_bg: '#E1EBEF',
      btn_disabled_text: '#8FA6AE',
      btn_disabled_border: '#E1EBEF',
      ...STATE_LIGHT,
    },
    dark: {
      bg: '#050F15',
      bg_2: '#09161E',
      surface: '#0C1C25',
      header_bg: '#050F15',
      footer_bg: '#050F15',
      heading_color: '#F3F5F7',
      body_text_color: '#F3F5F7',
      secondary_text_color: '#97A5AE',
      muted_text_color: '#73838C',
      link_color: '#38BDF8',
      icon_color: '#38BDF8',
      btn_fill_bg: '#38BDF8',
      btn_fill_bg_hover: '#63CBFA',
      btn_fill_bg_active: '#1EA7E8',
      btn_fill_text: '#051923',
      btn_fill_border: '#38BDF8',
      btn_ghost_text: '#F3F5F7',
      btn_ghost_border: '#223D4C',
      btn_ghost_border_hover: '#73838C',
      btn_disabled_bg: '#162B36',
      btn_disabled_text: '#73838C',
      btn_disabled_border: '#162B36',
      ...STATE_DARK,
    },
  },
  {
    key: 'charcoal_mono',
    labelKey: 'theme.preset.charcoalMono',
    light: {
      bg: '#FAFAFA',
      bg_2: '#F0F0F0',
      surface: '#FFFFFF',
      header_bg: '#FAFAFA',
      footer_bg: '#FAFAFA',
      heading_color: '#171717',
      body_text_color: '#171717',
      secondary_text_color: '#404040',
      muted_text_color: '#737373',
      link_color: '#262626',
      icon_color: '#262626',
      btn_fill_bg: '#262626',
      btn_fill_bg_hover: '#171717',
      btn_fill_bg_active: '#0A0A0A',
      btn_fill_text: '#FFFFFF',
      btn_fill_border: '#262626',
      btn_ghost_text: '#171717',
      btn_ghost_border: '#D4D4D4',
      btn_ghost_border_hover: '#737373',
      btn_disabled_bg: '#E5E5E5',
      btn_disabled_text: '#A3A3A3',
      btn_disabled_border: '#E5E5E5',
      ...STATE_LIGHT,
    },
    dark: {
      bg: '#0A0A0A',
      bg_2: '#171717',
      surface: '#212121',
      header_bg: '#0A0A0A',
      footer_bg: '#0A0A0A',
      heading_color: '#FAFAFA',
      body_text_color: '#FAFAFA',
      secondary_text_color: '#D4D4D4',
      muted_text_color: '#A3A3A3',
      link_color: '#E5E5E5',
      icon_color: '#E5E5E5',
      btn_fill_bg: '#E5E5E5',
      btn_fill_bg_hover: '#FFFFFF',
      btn_fill_bg_active: '#D4D4D4',
      btn_fill_text: '#171717',
      btn_fill_border: '#E5E5E5',
      btn_ghost_text: '#FAFAFA',
      btn_ghost_border: '#404040',
      btn_ghost_border_hover: '#A3A3A3',
      btn_disabled_bg: '#262626',
      btn_disabled_text: '#737373',
      btn_disabled_border: '#262626',
      ...STATE_DARK,
    },
  },
  {
    key: 'warm_terracotta',
    labelKey: 'theme.preset.warmTerracotta',
    light: {
      bg: '#FDF6EE',
      bg_2: '#F7EBDD',
      surface: '#FFFFFF',
      header_bg: '#FDF6EE',
      footer_bg: '#FDF6EE',
      heading_color: '#3B1F14',
      body_text_color: '#3B1F14',
      secondary_text_color: '#6B4530',
      muted_text_color: '#957A65',
      link_color: '#C2410C',
      icon_color: '#C2410C',
      btn_fill_bg: '#C2410C',
      btn_fill_bg_hover: '#9A3409',
      btn_fill_bg_active: '#7C2D0C',
      btn_fill_text: '#FFFFFF',
      btn_fill_border: '#C2410C',
      btn_ghost_text: '#3B1F14',
      btn_ghost_border: '#E7D2BC',
      btn_ghost_border_hover: '#957A65',
      btn_disabled_bg: '#F0E2D0',
      btn_disabled_text: '#A9926F',
      btn_disabled_border: '#F0E2D0',
      ...STATE_LIGHT,
    },
    dark: {
      bg: '#1C120B',
      bg_2: '#26180F',
      surface: '#301E13',
      header_bg: '#1C120B',
      footer_bg: '#1C120B',
      heading_color: '#FBEEE0',
      body_text_color: '#FBEEE0',
      secondary_text_color: '#D8B79B',
      muted_text_color: '#A98868',
      link_color: '#F97316',
      icon_color: '#F97316',
      btn_fill_bg: '#F97316',
      btn_fill_bg_hover: '#FB923C',
      btn_fill_bg_active: '#EA580C',
      btn_fill_text: '#2A1206',
      btn_fill_border: '#F97316',
      btn_ghost_text: '#FBEEE0',
      btn_ghost_border: '#4A3220',
      btn_ghost_border_hover: '#A98868',
      btn_disabled_bg: '#3A2718',
      btn_disabled_text: '#8A6F55',
      btn_disabled_border: '#3A2718',
      ...STATE_DARK,
    },
  },
  {
    key: 'forest_green',
    labelKey: 'theme.preset.forestGreen',
    light: {
      bg: '#F5FAF6',
      bg_2: '#E9F4EB',
      surface: '#FFFFFF',
      header_bg: '#F5FAF6',
      footer_bg: '#F5FAF6',
      heading_color: '#0F2B1A',
      body_text_color: '#0F2B1A',
      secondary_text_color: '#305840',
      muted_text_color: '#628068',
      link_color: '#15803D',
      icon_color: '#15803D',
      btn_fill_bg: '#15803D',
      btn_fill_bg_hover: '#116530',
      btn_fill_bg_active: '#0D4F26',
      btn_fill_text: '#FFFFFF',
      btn_fill_border: '#15803D',
      btn_ghost_text: '#0F2B1A',
      btn_ghost_border: '#C7E0CC',
      btn_ghost_border_hover: '#628068',
      btn_disabled_bg: '#DDEEE0',
      btn_disabled_text: '#8FAC94',
      btn_disabled_border: '#DDEEE0',
      ...STATE_LIGHT,
    },
    dark: {
      bg: '#071510',
      bg_2: '#0C2017',
      surface: '#12291D',
      header_bg: '#071510',
      footer_bg: '#071510',
      heading_color: '#EAF7ED',
      body_text_color: '#EAF7ED',
      secondary_text_color: '#A8CBB0',
      muted_text_color: '#7DA087',
      link_color: '#22C55E',
      icon_color: '#22C55E',
      btn_fill_bg: '#22C55E',
      btn_fill_bg_hover: '#4ADE80',
      btn_fill_bg_active: '#16A34A',
      btn_fill_text: '#052E14',
      btn_fill_border: '#22C55E',
      btn_ghost_text: '#EAF7ED',
      btn_ghost_border: '#234533',
      btn_ghost_border_hover: '#7DA087',
      btn_disabled_bg: '#1A3627',
      btn_disabled_text: '#6E8F76',
      btn_disabled_border: '#1A3627',
      ...STATE_DARK,
    },
  },
]
